hostgroups:
- groupname: hostgroup03 
  authmethod: method02 
  sshport: 22
  hosts:
  - 192.168.31.37

- groupname: hostgroup01
  authmethod: method01
  sshport: 22
  hosts:
  - 192.168.31.63
  - 192.168.31.37

- groupname: OM-Base
  authmethod: paas
  sshport: 22
  hosts:
  - 192.145.65.119
