hostgroups:
- groupname: test-group01                 #Hostgroup name
  authmethod: alpha-env-ttt-key-su        #Hostgrout auth method name which in auth.yaml
  sshport: 22                             #SSH port, default: 22
  hosts:
  - 192.168.31.37                         #Ipv4 format
  - 192.168.31.63

- groupname: hostgroup02
  authmethod: alpha-env-root-key
  sshport: 22
  hosts:
  - 192.168.31.37

- groupname: hostgroup03
  authmethod: alpha-env-root-pass
  sshport: 22
  hosts:
  - 192.168.31.63

- groupname: test-group03
  authmethod: alpha-env-root-pass
  sshport: 22
  groups:
  - hostgroup02
  - hostgroup03
  hosts:
  - 192.168.31.78
  hostranges:
  - from: 192.168.31.90
    to: 192.168.31.92